### ISSUE TITLE
sql file missing

### ISSUE THREAD

**Issue by vimgau28** [Nsima/A-Simple-HYIP-PHP-Script#1]
thier is no .sql 
upload database .sql file

**Comment by Nsima** [comment]
Totally forgot...

**Comment by vimgau28** [comment]
This folder is not a .sql file
this is database.php not a database.sql

**Comment by vimgau28** [comment]
i am learner i have no any sound knowledge. please explain step by step installation instruction
I would be very grateful if you shared the latest script

**Comment by Nsima** [comment]
Its been long since I worked on this script, you'd have to tell me what issues you are encountering and I would be very glad to help. 
To install, follow the instructions on the readme.md and you should be fine. If there are any other issues, you let me know.

**Comment by vimgau28** [comment]
Folder does not have sql file
Here's only the database.php file
where is sql file

**Comment by Nsima** [comment]
There is a database.sql file in the root. I uploaded it today.

**Comment by vimgau28** [comment]
ok, fine I have got it

**Comment by vimgau28** [comment]
i installed script getting error 404

**Comment by vimgau28** [comment]
/pages/index.html  not found
and
some files or code missing

**Comment by Nsima** [comment]
I have uploaded a zip file, 'cash.zip'. It contains the updated source code. Extract and replace with the source code in your htdocs.

**Comment by vimgau28** [comment]
ok,

**Comment by vimgau28** [comment]
How to install it I am uploading to shared hosting.
there is no ssh access permission

**Comment by Nsima** [comment]
That seems to me like a problem with your host permissions.
Or you might have uploaded the files wrongly...

**Comment by vimgau28** [comment]
can i install it on shared hosting its compitable for shared hosting or not

**Comment by Nsima** [comment]
Yes, you can install on a shared host.

**Comment by vimgau28** [comment]
its need composer to install

**Comment by Nsima** [comment]
It doesn't need composer to install. What hosting provider are you using?

**Comment by vimgau28** [comment]
byethost.com  
without installation look like this  http://zigzag.fanclub.rocks

**Comment by vimgau28** [comment]
byethost.com
without installation look like this http://zigzag.fanclub.rocks

**Comment by Nsima** [comment]
Thats practically it. Send me a mail georgensima@gmail.com.
